using MultiTypeParameterGenerator.Common.Models.Entities;
using MultiTypeParameterGenerator.Common.Utils;

namespace MultiTypeParameterGenerator.Tests.UnitTests.Common.Models.Entities;

public static class SourceCodeFileTest
{
    public sealed class SourceCodeProperty
    {
        [Fact]
        public void ReturnsSourceCodeWithAutoGeneratedHeader()
        {
            // Arrange
            var sourceFile = new SourceCodeFile(new("TestFile.cs"), new("class C;"));

            // Act & Assert
            sourceFile.SourceCode.Value.Should().Be($"{Constants.SourceGeneratedFileHeader}class C;");
        }
    }
}