using MultiTypeParameterGenerator.Common.Models.TypedValues;

namespace MultiTypeParameterGenerator.Common.Utils;

internal static class Constants
{
    internal const string NewLine = "\n";
    internal const string DoubleNewLine = $"{NewLine}{NewLine}";

    internal const string Tab = "   ";
    internal const string DoubleTab = $"{Tab}{Tab}";

    internal const string Whitespace = " ";

    internal const string ThisIdentifier = "@this";

    internal static readonly SourceCode SourceGeneratedFileHeader =
        new("""
            // <auto-generated/>
            // ReSharper disable All
            #nullable enable


            """);
}