namespace MultiTypeParameterGenerator;

/// <summary>
///     Defines the available access modifiers for generated method overloads.
/// </summary>
public enum AccessModifier
{
    /// <summary>
    ///     Indicates public access - the method will be accessible from any code.
    /// </summary>
    Public,

    /// <summary>
    ///     Indicates protected access - the method will be accessible only within the containing class and derived classes.
    /// </summary>
    Protected,

    /// <summary>
    ///     Indicates internal access - the method will be accessible only within the same assembly.
    /// </summary>
    Internal,

    /// <summary>
    ///     Indicates protected internal access - the method will be accessible within the same assembly and by derived
    ///     classes.
    /// </summary>
    ProtectedInternal,

    /// <summary>
    ///     Indicates private protected access - the method will be accessible only within the containing class and derived
    ///     classes in the same assembly.
    /// </summary>
    PrivateProtected
}

/// <summary>
///     An attribute used to specify the access modifiers for generated method overloads.
///     This attribute should be applied to methods that will have code generated by the MultiTypeParameterGenerator.
/// </summary>
[AttributeUsage(AttributeTargets.Method)]
#pragma warning disable CS9113 // Parameter is unread.
public sealed class AccessModifiersAttribute(AccessModifier accessModifiers) : Attribute;
#pragma warning restore CS9113 // Parameter is unread.