namespace MultiTypeParameterGenerator;

/// <summary>
///     An attribute used to specify if fully qualified names should be used in methods generated by the
///     MultiTypeParameterGenerator.
/// </summary>
[AttributeUsage(AttributeTargets.Assembly)]
public sealed class UseFullTypeNamesAttribute : Attribute;